# ----------------------------------------------------------------------------
# Copyright (c) 2021, Diego Garcia Huerta.
#
# Your use of this software as distributed in this GitHub repository, is
# governed by the MIT License
#
# Your use of the Shotgun Pipeline Toolkit is governed by the applicable
# license agreement between you and Autodesk / Shotgun.
#
# Read LICENSE and SHOTGUN_LICENSE for full details about the licenses that
# pertain to this software.
# ----------------------------------------------------------------------------


# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your asset.yml environment file, as
# THIS FILE BY ITSELF WILL NOT WORK
# These are the additions to get the engine up and running with the
# default tk-apps for this file

# Rumba
engines.tk-rumba.location:
  type: git
  path: https://github.com/diegogarciahuerta/tk-rumba
  version: v1.0.0
