# ----------------------------------------------------------------------------
# Copyright (c) 2021, Diego Garcia Huerta.
#
# Your use of this software as distributed in this GitHub repository, is
# governed by the MIT License
#
# Your use of the Shotgun Pipeline Toolkit is governed by the applicable
# license agreement between you and Autodesk / Shotgun.
#
# Read LICENSE and SHOTGUN_LICENSE for full details about the licenses that
# pertain to this software.
# ----------------------------------------------------------------------------


# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your template.yml configuration file, as
# THIS FILE BY ITSELF WILL NOT WORK
# These are the additions to the template.yml to get the engine up and
# running with the default tk-apps


keys:
    # ---- Rumba
    rumba.node.name:
        type: str

paths:
    #
    # Rumba
    #

    # asset
    # define the location of a work area
    asset_work_area_rumba:
        definition: '@asset_root/work/rumba'
        root_name: 'primary'

    # define the location of a publish area
    asset_publish_area_rumba:
        definition: '@asset_root/publish/rumba'
        root_name: 'primary'

    # The location of WIP files
    rumba_asset_work:
        definition: '@asset_work_area_rumba/{name}.v{version}.rumba'
        root_name: 'primary'

    # The location of backups of WIP files
    rumba_asset_snapshot:
        definition: '@asset_work_area_rumba/snapshots/{name}.v{version}.{timestamp}.rumba'
        root_name: 'primary'

    # The location of published rumba files
    rumba_asset_publish:
        definition: '@asset_publish_area_rumba/{name}.v{version}.rumba'
        root_name: 'primary'

    # Animation as USD
    rumba_asset_usd:
        definition: '@asset_publish_area_rumba/animation/{name}_animation.v{version}.usd'
        root_name: 'primary'

    # Animation as fbx
    rumba_asset_fbx_animation:
        definition: '@asset_publish_area_rumba/animation/{name}_animation.v{version}.fbx'
        root_name: 'primary'

    # Animation as Alembic Cache
    rumba_asset_alembic_cache_animation:
        definition: '@asset_publish_area_rumba/caches/{name}_animation.v{version}.abc'
        root_name: 'primary'

    # Selected node as Rumba Node
    rumba_asset_rumba_node:
        definition: '@asset_publish_area_rumba/nodes/{name}_{rumba.node.name}.v{version}.rumbanode'
        root_name: 'primary'

    # shot
    # define the location of a work area
    shot_work_area_rumba:
        definition: '@shot_root/work/rumba'
        root_name: 'primary'
    # define the location of a publish area
    shot_publish_area_rumba:
        definition: '@shot_root/publish/rumba'
        root_name: 'primary'
    # The location of WIP files
    rumba_shot_work:
        definition: '@shot_work_area_rumba/rumba/{name}.v{version}.rumba'
        root_name: 'primary'
    # The location of backups of WIP files
    rumba_shot_snapshot:
        definition: '@shot_work_area_rumba/rumba/snapshots/{name}.v{version}.{timestamp}.rumba'
        root_name: 'primary'
    # The location of published rumba files
    rumba_shot_publish:
        definition: '@shot_publish_area_rumba/rumba/{name}.v{version}.rumba'
        root_name: 'primary'

    # Animation as USD
    rumba_shot_usd:
        definition: '@shot_publish_area_rumba/animation/{name}_animation.v{version}.usd'
        root_name: 'primary'

    # Animation as fbx
    rumba_shot_fbx_animation:
        definition: '@shot_publish_area_rumba/animation/{name}_animation.v{version}.fbx'
        root_name: 'primary'

    # Animation as Alembic Cache
    rumba_shot_alembic_cache_animation:
        definition: '@shot_publish_area_rumba/caches/{name}_animation.v{version}.abc'
        root_name: 'primary'
